name: decamelize
version: 0.1.1
description: >-
  A Dart package to easily decamelize strings. 
  Î™nspiration by the homonymous npm package https://www.npmjs.com/package/decamelize
homepage: https://github.com/hectortav/decamelize
environment:
  sdk: '>=2.6.0 <3.0.0'